export const BOOKING_LIST_REQUEST = "BOOKING_LIST_REQUEST";
export const BOOKING_LIST_SUCCESS = "BOOKING_LIST_SUCCESS";
export const BOOKING_LIST_FAIL = "BOOKING_LIST_FAIL";

export const BOOKING_DETAILS_REQUEST = "BOOKING_DETAILS_REQUEST";
export const BOOKING_DETAILS_SUCCESS = "BOOKING_DETAILS_SUCCESS";
export const BOOKING_DETAILS_FAIL = "BOOKING_DETAILS_FAIL";

export const BOOKING_ISPAID_REQUEST = "BOOKING_ISPAID_REQUEST";
export const BOOKING_ISPAID_SUCCESS = "BOOKING_ISPAID_SUCCESS";
export const BOOKING_ISPAID_FAIL = "BOOKING_ISPAID_FAIL";
export const BOOKING_ISPAID_RESET = "BOOKING_ISPAID_RESET";

export const BOOKING_NOTPAID_REQUEST = "BOOKING_NOTPAID_REQUEST";
export const BOOKING_NOTPAID_SUCCESS = "BOOKING_NOTPAID_SUCCESS";
export const BOOKING_NOTPAID_FAIL = "BOOKING_NOTPAID_FAIL";
export const BOOKING_NOTPAID_RESET = "BOOKING_NOTPAID_RESET";

export const BOOKING_ISCONFIRMED_REQUEST = "BOOKING_ISCONFIRMED_REQUEST";
export const BOOKING_ISCONFIRMED_SUCCESS = "BOOKING_ISCONFIRMED_SUCCESS";
export const BOOKING_ISCONFIRMED_FAIL = "BOOKING_ISCONFIRMED_FAIL";
export const BOOKING_ISCONFIRMED_RESET = "BOOKING_ISCONFIRMED_RESET";

export const BOOKING_ISCHECKOUT_REQUEST = "BOOKING_ISCHECKOUT_REQUEST";
export const BOOKING_ISCHECKOUT_SUCCESS = "BOOKING_ISCHECKOUT_SUCCESS";
export const BOOKING_ISCHECKOUT_FAIL = "BOOKING_ISCHECKOUT_FAIL";
export const BOOKING_ISCHECKOUT_RESET = "BOOKING_ISCHECKOUT_RESET";

export const BOOKING_DELETE_REQUEST = "BOOKING_DELETE_REQUEST";
export const BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS";
export const BOOKING_DELETE_FAIL = "BOOKING_DELETE_FAIL";