export const RAFTBOAT_LIST_REQUEST = "RAFTBOAT_LIST_REQUEST";
export const RAFTBOAT_LIST_SUCCESS = "RAFTBOAT_LIST_SUCCESS";
export const RAFTBOAT_LIST_FAIL = "RAFTBOAT_LIST_FAIL";
export const RAFTBOAT_LIST_RESET = "RAFTBOAT_LIST_RESET";

export const RAFTBOAT_EDIT_REQUEST = "RAFTBOAT_EDIT_REQUEST";
export const RAFTBOAT_EDIT_SUCCESS = "RAFTBOAT_EDIT_SUCCESS";
export const RAFTBOAT_EDIT_FAIL = "RAFTBOAT_EDIT_FAIL";
export const RAFTBOAT_EDIT_RESET = "RAFTBOAT_EDIT_RESET";

export const RAFTBOAT_CREATE_REQUEST = "RAFTBOAT_CREATE_REQUEST";
export const RAFTBOAT_CREATE_SUCCESS = "RAFTBOAT_CREATE_SUCCESS";
export const RAFTBOAT_CREATE_FAIL = "RAFTBOAT_CREATE_FAIL";
export const RAFTBOAT_CREATE_RESET = "RAFTBOAT_CREATE_RESET";

export const RAFTBOAT_UPDATE_REQUEST = "RAFTBOAT_UPDATE_REQUEST";
export const RAFTBOAT_UPDATE_SUCCESS = "RAFTBOAT_UPDATE_SUCCESS";
export const RAFTBOAT_UPDATE_FAIL = "RAFTBOAT_UPDATE_FAIL";
export const RAFTBOAT_UPDATE_RESET = "RAFTBOAT_UPDATE_RESET";

export const RAFTBOAT_DELETE_REQUEST = "RAFTBOAT_DELETE_REQUEST";
export const RAFTBOAT_DELETE_SUCCESS = "RAFTBOAT_DELETE_SUCCESS";
export const RAFTBOAT_DELETE_FAIL = "RAFTBOAT_DELETE_FAIL";